name: mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.3.2

  # UI & FONTS

  # PERMISSION HANDLING
  
  # STORAGE & FILE HANDLING
  
  # LOCATION & SENSORS
  location: ^5.0.3
  
  # DEVICE INFO (ADD THIS)
  device_info_plus: ^9.1.0
  
  # BACKGROUND PROCESSING
  workmanager: ^0.9.0+3
  
  # BLUETOOTH
  
  # BATTERY OPTIMIZATION
  disable_battery_optimization: ^1.1.1
  
  # NOTIFICATIONS
  flutter_local_notifications: ^16.3.0
  
  # ANALYTICS & TRACKING
  package_info_plus: ^4.2.0

  cupertino_icons: ^1.0.8
  simple_animations: ^5.0.2
  google_fonts: ^6.2.1
  model_viewer_plus: ^1.7.0
  lottie: ^3.3.1
  uuid: ^4.5.1
  intl: ^0.20.2
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  fl_chart: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.2.0
  http_parser: ^4.1.2
  sensors_plus: ^4.0.2
  geolocator: ^10.1.0
  mime: ^1.0.5 
  socket_io_client: ^3.1.2
  share_plus: ^7.2.1
  flutter_sound: ^9.2.13
  flutter_riverpod: ^2.6.1
  permission_handler: ^11.1.0
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  flutter_styled_toast: ^2.2.1
  firebase_core: ^4.1.0
  go_router: ^16.2.1
  app_links: ^6.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  connectivity_plus: ^5.0.2
  rxdart: ^0.28.0
  flutter_bluetooth_serial: ^0.4.0
  network_info_plus: ^7.0.0
  open_file: ^3.3.2
  mapbox_maps_flutter: ^2.11.0
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/animations/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo1.png"